name: CI
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        # python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-22.04]
        # os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env: 
      RUYI: poetry run python ./src/anrsm/cli.py
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: prepare
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: ruyi hullo
        run: |
          $RUYI hullo
      - name: ruyi config
        run: |
          $RUYI config set softlink ~/softlink
          $RUYI config get softlink
      - name: ruyi sourse
        run: |
          $RUYI source update
          $RUYI source list
      - name: create dir
        run: |
          mkdir ~/softlink
          mkdir ~/target
      - name: ruyi sourse
        run: |
          $RUYI source cache plct@20231110
          $RUYI source expand plct@20231110 ~/target --softlink